version: '3.2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
    - "80:80"
    volumes:
    - ./sample-app/public:/srv/www/sample-app/public:cached
    restart: always
    tty: true
    read_only: false
    privileged: true

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    depends_on:
      - mysql
      - mail
    volumes:
    - ./sample-app:/srv/www/sample-app:cached
    restart: always
    tty: true
    read_only: false
    privileged: true

  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    volumes:
    - .:/build
    working_dir: /build

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
    - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    restart: always
    tty: true
    read_only: false
    privileged: true

  mail:
    image: mailhog/mailhog
    ports:
    - "8025:8025"
    - "1025:1025"
    restart: always
    tty: true
    read_only: false
    privileged: true

volumes:
  mysql-data: